import express from "express";
import fetch from "node-fetch";
import fs from "fs-extra";
import path from "path";

const router = express.Router();

// ✅ EXPORT PROJECT TO GITHUB
router.post("/github", async (req, res) => {
  const { token, repoName, html } = req.body;
  if (!token || !repoName || !html)
    return res.status(400).json({ error: "Missing required fields" });

  try {
    // 1️⃣ Create a GitHub repo
    const createRepo = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: repoName,
        description: "Generated by ArjunAI 🚀",
        auto_init: true,
      }),
    });

    const repo = await createRepo.json();
    if (!repo.full_name) throw new Error(repo.message || "Failed to create repo");

    // 2️⃣ Add index.html
    const content = Buffer.from(html).toString("base64");
    const pushFile = await fetch(
      `https://api.github.com/repos/${repo.full_name}/contents/index.html`,
      {
        method: "PUT",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: "Add generated website via ArjunAI",
          content,
        }),
      }
    );

    const result = await pushFile.json();
    if (result?.commit) {
      res.json({
        success: true,
        repoUrl: repo.html_url,
        message: "✅ Repo created and HTML uploaded successfully!",
      });
    } else {
      throw new Error("Failed to upload file");
    }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ✅ OPTIONAL — DEPLOY TO VERCEL
router.post("/vercel", async (req, res) => {
  const { html, projectName, vercelToken } = req.body;
  if (!html || !projectName || !vercelToken)
    return res.status(400).json({ error: "Missing required fields" });

  try {
    const tmpDir = path.join(process.cwd(), "tmp", projectName);
    await fs.ensureDir(tmpDir);
    await fs.writeFile(path.join(tmpDir, "index.html"), html);

    const response = await fetch("https://api.vercel.com/v13/deployments", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${vercelToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: projectName,
        files: [
          {
            file: "index.html",
            data: html,
          },
        ],
        target: "production",
      }),
    });

    const data = await response.json();
    res.json({ success: true, url: data?.url || null });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

export default router;
